# Generated by Django 5.2.8 on 2025-11-14 09:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLogCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_id', models.CharField(db_index=True, max_length=100)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('locations_data', models.JSONField()),
                ('total_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'geo_log_cache',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['distribution_id', 'start_date', 'end_date', 'expires_at'], name='geo_log_cac_distrib_0eb444_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPGeolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45, unique=True)),
                ('continent', models.CharField(blank=True, max_length=100, null=True)),
                ('continent_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
                ('offset', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('isp', models.CharField(blank=True, max_length=255, null=True)),
                ('org', models.CharField(blank=True, max_length=255, null=True)),
                ('asn', models.CharField(blank=True, max_length=100, null=True)),
                ('asname', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.BooleanField(blank=True, null=True)),
                ('proxy', models.BooleanField(blank=True, null=True)),
                ('hosting', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hit_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ip_geolocation_cache',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='ip_geolocat_ip_addr_359279_idx')],
            },
        ),
        migrations.CreateModel(
            name='WAFBlockedIPSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_id', models.CharField(db_index=True, max_length=100)),
                ('snapshot_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_ips', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'waf_blocked_ip_snapshots',
                'ordering': ['-snapshot_time'],
                'indexes': [models.Index(fields=['distribution_id', 'snapshot_time'], name='waf_blocked_distrib_c20a6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WAFBlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=45)),
                ('cidr', models.CharField(max_length=50)),
                ('ip_set_id', models.CharField(max_length=100)),
                ('ip_set_name', models.CharField(max_length=255)),
                ('ip_set_arn', models.TextField()),
                ('geolocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ipgeolocation')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_ips', to='api.wafblockedipsnapshot')),
            ],
            options={
                'db_table': 'waf_blocked_ips',
                'ordering': ['ip_address'],
                'indexes': [models.Index(fields=['snapshot', 'ip_address'], name='waf_blocked_snapsho_94bda4_idx')],
            },
        ),
    ]
