# Generated by Django 5.2.8 on 2025-11-14 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedLogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_id', models.CharField(db_index=True, max_length=100)),
                ('log_file_key', models.CharField(db_index=True, max_length=500, unique=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('record_count', models.IntegerField(default=0)),
                ('log_start_time', models.DateTimeField(blank=True, null=True)),
                ('log_end_time', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'processed_log_files',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['distribution_id', 'log_start_time', 'log_end_time'], name='processed_l_distrib_ebecc9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_id', models.CharField(db_index=True, max_length=100)),
                ('log_datetime', models.DateTimeField(db_index=True)),
                ('edge_location', models.CharField(blank=True, max_length=50, null=True)),
                ('c_ip', models.GenericIPAddressField(db_index=True)),
                ('cs_method', models.CharField(blank=True, max_length=10, null=True)),
                ('cs_host', models.CharField(blank=True, max_length=255, null=True)),
                ('cs_uri_stem', models.CharField(blank=True, max_length=2000, null=True)),
                ('cs_uri_query', models.TextField(blank=True, null=True)),
                ('sc_status', models.IntegerField(blank=True, db_index=True, null=True)),
                ('sc_bytes', models.BigIntegerField(blank=True, null=True)),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('cs_user_agent', models.TextField(blank=True, null=True)),
                ('cs_referer', models.TextField(blank=True, null=True)),
                ('x_edge_result_type', models.CharField(blank=True, max_length=50, null=True)),
                ('geolocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ipgeolocation')),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.processedlogfile')),
            ],
            options={
                'db_table': 'access_logs',
                'ordering': ['-log_datetime'],
                'indexes': [models.Index(fields=['distribution_id', 'log_datetime'], name='access_logs_distrib_8b82ea_idx'), models.Index(fields=['c_ip', 'log_datetime'], name='access_logs_c_ip_ed4dbd_idx'), models.Index(fields=['log_file', 'log_datetime'], name='access_logs_log_fil_c88a7b_idx')],
            },
        ),
    ]
