# Generated by Django 5.2.8 on 2025-11-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_processedlogfile_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='geologcache',
            name='actual_end_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='geologcache',
            name='actual_start_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='geologcache',
            index=models.Index(fields=['distribution_id', 'actual_start_datetime', 'actual_end_datetime'], name='geo_log_cac_distrib_da8bb0_idx'),
        ),
    ]
