# Generated by Django 5.2.8 on 2025-11-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_geologcache_actual_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geologcache',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
