# Generated by Django 5.2.8 on 2025-11-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_geologcache_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipgeolocation',
            name='whois_country',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ipgeolocation',
            name='whois_net_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ipgeolocation',
            name='whois_netname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ipgeolocation',
            name='whois_org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ipgeolocation',
            name='whois_raw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
