# Generated by Django 5.2.8 on 2025-11-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ipgeolocation_whois_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='cs_method',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='cs_uri_stem',
            field=models.CharField(blank=True, db_index=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='ipgeolocation',
            name='hit_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ipgeolocation',
            name='whois_netname',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ipgeolocation',
            name='whois_org_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ipgeolocation',
            name='whois_raw',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['distribution_id', 'cs_method', 'sc_status'], name='access_logs_distrib_e277b7_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['distribution_id', 'log_datetime', 'sc_status'], name='access_logs_distrib_319887_idx'),
        ),
    ]
