# Generated by Django 5.2.8 on 2025-11-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_accesslog_cs_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='asn',
            field=models.IntegerField(blank=True, db_index=True, help_text='自律システム番号（v2のみ）', null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='c_country',
            field=models.CharField(blank=True, db_index=True, help_text='国コード ISO 3166-1 alpha-2（v2のみ）', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='cache_behavior_path_pattern',
            field=models.CharField(blank=True, help_text='マッチしたキャッシュ動作パターン（v2のみ）', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='origin_fbl',
            field=models.FloatField(blank=True, help_text='Origin first-byte latency in seconds（v2のみ）', null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='origin_lbl',
            field=models.FloatField(blank=True, help_text='Origin last-byte latency in seconds（v2のみ）', null=True),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='timestamp_ms',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ミリ秒精度のUnixタイムスタンプ（v2のみ）', null=True),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['timestamp_ms'], name='access_logs_timesta_eb9b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['asn'], name='access_logs_asn_24733d_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['c_country'], name='access_logs_c_count_2fa9a1_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['distribution_id', 'c_country'], name='access_logs_distrib_d451df_idx'),
        ),
    ]
