# Generated by Django 5.2.8 on 2025-12-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_v2_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMarkPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_id', models.CharField(blank=True, db_index=True, help_text='対象のDistribution ID（省略時は全Distribution対象）', max_length=100, null=True)),
                ('user_agent_pattern', models.CharField(db_index=True, help_text='マッチング対象のUser-Agentパターン', max_length=500)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('partial', 'Partial Match')], default='partial', help_text='マッチング方法', max_length=10)),
                ('mark_type', models.CharField(choices=[('bot', 'Bot'), ('suspicious', 'Suspicious'), ('legitimate', 'Legitimate')], db_index=True, help_text='マークの種類', max_length=20)),
                ('note', models.TextField(blank=True, help_text='メモ・説明', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='アクティブフラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Log Mark Pattern',
                'verbose_name_plural': 'Log Mark Patterns',
                'db_table': 'log_mark_patterns',
                'ordering': ['-created_at'],
            },
        ),
    ]
