# Generated by Django 5.2.8 on 2025-12-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_logmarkpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmarkpattern',
            name='ip_pattern',
            field=models.CharField(blank=True, db_index=True, help_text='マッチング対象のIPアドレスパターン', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logmarkpattern',
            name='path_pattern',
            field=models.CharField(blank=True, db_index=True, help_text='マッチング対象のパスパターン', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logmarkpattern',
            name='query_string_pattern',
            field=models.CharField(blank=True, db_index=True, help_text='マッチング対象のクエリストリングパターン', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logmarkpattern',
            name='referrer_pattern',
            field=models.CharField(blank=True, db_index=True, help_text='マッチング対象のリファラパターン', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='logmarkpattern',
            name='user_agent_pattern',
            field=models.CharField(blank=True, db_index=True, help_text='マッチング対象のUser-Agentパターン', max_length=500, null=True),
        ),
    ]
