# Generated by Django 5.2.8 on 2025-12-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_logmarkpattern_ip_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmarkpattern',
            name='org_pattern',
            field=models.CharField(blank=True, db_index=True, help_text='マッチング対象の組織名パターン（IPGeolocationのorg/isp/asnameと照合）', max_length=255, null=True),
        ),
    ]
