# Generated by Django 5.2.8 on 2025-12-03 11:26

import django.db.models.deletion
from django.db import migrations, models


def create_default_categories(apps, schema_editor):
    """初期カテゴリを作成"""
    LogMarkCategory = apps.get_model("api", "LogMarkCategory")

    categories = [
        {"name": "ボット", "slug": "bot", "color": "#22C55E", "description": "許可されたボット・クローラー"},
        {"name": "不審", "slug": "suspicious", "color": "#EAB308", "description": "不審なアクセス"},
        {"name": "ブロック", "slug": "blocked", "color": "#EF4444", "description": "ブロック対象"},
    ]

    for cat in categories:
        LogMarkCategory.objects.get_or_create(slug=cat["slug"], defaults=cat)


def delete_existing_patterns(apps, schema_editor):
    """既存のパターンを削除（mark_typeカラム削除前に必要）"""
    LogMarkPattern = apps.get_model("api", "LogMarkPattern")
    LogMarkPattern.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_logmarkpattern_org_pattern"),
    ]

    operations = [
        # 1. LogMarkCategoryテーブルを作成
        migrations.CreateModel(
            name="LogMarkCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="カテゴリ名（表示用）", max_length=100),
                ),
                (
                    "slug",
                    models.CharField(
                        db_index=True,
                        help_text="カテゴリのスラッグ（識別子）",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="表示色（HEXカラーコード）",
                        max_length=7,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="説明", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Log Mark Category",
                "verbose_name_plural": "Log Mark Categories",
                "db_table": "log_mark_categories",
                "ordering": ["name"],
            },
        ),
        # 2. 初期カテゴリを作成
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
        # 3. 既存パターンを削除
        migrations.RunPython(delete_existing_patterns, migrations.RunPython.noop),
        # 4. mark_typeカラムを削除
        migrations.RemoveField(
            model_name="logmarkpattern",
            name="mark_type",
        ),
        # 5. categoryカラムを追加（null許可）
        migrations.AddField(
            model_name="logmarkpattern",
            name="category",
            field=models.ForeignKey(
                help_text="マークのカテゴリ",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patterns",
                to="api.logmarkcategory",
            ),
        ),
    ]
